### ISSUE TITLE
Jasmine-rails test rig setup.

### ISSUE THREAD

**Issue by johnelliott** [johnelliott/Waybot-Legacy#14]
I'm trying to set up Jasmine-rails to test my backbone code. I'd like to add run starting/stopping and using tdd/bdd seems like the best way to figure it out. I'm having trouble setting up my tests for my client-side javascript. This is all without any relation to my application logic. The test assertion hasn't even run when this error appears.

The test: [https://github.com/johnelliott/Waybot/blob/feat-run-recording/spec/javascripts/hitsSpec.js](https://github.com/johnelliott/Waybot/blob/feat-run-recording/spec/javascripts/hitsSpec.js)

I think part of the problem might be my test setup or jasmine installation, but I can't nail down the source of the problem. I'm running the following command to run my tests and getting the output down below

```
RAILS_ENV=test bundle exec rake spec:javascript
```

Output:

```
Running `"/usr/local/bin/phantomjs" "/Users/john/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jasmine-rails-0.10.2/lib/jasmine_rails/../assets/javascripts/jasmine-runner.js" "/Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/runner.html?spec="`
Running: /Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/runner.html?spec=
ERROR: TypeError: 'undefined' is not a function (evaluating 'callback($)')
TRACE:
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 11463
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 4642
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 4310
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 4551
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 5261
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 384
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 137
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 5262
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 11468
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 3120
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 3232
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 3444
 -> file:///Users/john/Dropbox/dev/projects/Waybot/wb-app/tmp/jasmine/assets/jasmine-specs.js: 3475 (in function "completed")
```

**Comment by johnelliott** [comment]
It is looking more like this is an asset pipeline or jasmine-rails issue.

**Comment by mattscilipoti** [comment]
I tried to setup the application, but I am getting this error when running the jasmine rake task:

```
ActionView::Template::Error: couldn't find file 'underscore'
```

How should I/we be managing the assets?

**Comment by jrhorn424** [comment]
Do you have a jasmine gem you're using? I don't see it in your Gemfile. _Edit_: Nevermind, wrong branch.

**Comment by jrhorn424** [comment]
I can't get to your same failing state. I have an issue in the controller layer. I suspect it might be related to signing in, but I'm not sure. I might be able to put more time into it tomorrow.

**Comment by jrhorn424** [comment]
I have the spec passing on your branch after resolving dependency issues. I'll open a PR.

**Comment by johnelliott** [comment]
Thanks Jeff, I got this all set up and have added guard-jasmine to run my tests for me.
